In [28]:
import tensorflow as tf
# print(tf.__version__)

2.1.0


tensorflow.python.data.ops.dataset_ops.DatasetV2

In [35]:


x_path = './sample/images/'
x_file_list = []
y_str_list = []
with open('./sample/sample_labels.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            line_count += 1
        else:
#             print(type(row), len(row), row[0], row[1].split('|'))
            line_count += 1
            x_file_list.append(x_path + row[0])
            y_str_list.append(row[1].split('|'))
    
print(len(x_file_list))
print(len(y_str_list))

5606
5606


In [36]:
print(x_file_list[1001])
print(y_str_list[0])

./sample/images/00005220_007.png
['Emphysema', 'Infiltration', 'Pleural_Thickening', 'Pneumothorax']


In [37]:
y_dict = {
    'Emphysema': 0, 
    'Infiltration': 1, 
    'Pleural_Thickening': 2, 
    'Pneumothorax': 3, 
    'Cardiomegaly': 4, 
    'Atelectasis': 5, 
    'Edema': 6, 
    'Effusion': 7, 
    'Consolidation': 8, 
    'Mass': 9, 
    'Nodule': 10, 
    'Fibrosis': 11, 
    'Pneumonia': 12, 
    'Hernia': 13
}
# stats_dict = {}
# for i in range(len(y_str_list)):
#     labels = y_str_list[i]
#     for label in labels:
#         if label in stats_dict:
#             stats_dict[label] += 1
#         else:
#             stats_dict[label] = 1
# print(stats_dict)
# print(len(stats_dict))
y_list = []
for i in range(len(y_str_list)):
    labels = [0] * 14
    for y_logit in y_str_list[i]:
        if y_logit == 'No Finding':
            continue
        labels[y_dict[y_logit]] = 1
    labels = tf.constant(labels)
    y_list.append(labels)
print(y_list[0:10])

[<tf.Tensor: shape=(14,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=(14,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)>, <tf.Tensor: shape=

In [50]:
# dataset_x = tf.data.Dataset.from_tensor_slices(tf.convert_to_tensor(x_file_list))
# dataset_y = tf.data.Dataset.from_tensor_slices(y_list)
dataset = tf.data.Dataset.from_tensor_slices((x_file_list, y_list))
# for x in dataset_x:
#     print(x)
#     break
def parse_fn(filename, label):
    img_str = tf.io.read_file(filename)
    img_dcd = tf.image.decode_png(img_str, channels=3)
    return img_dcd, label
dataset = dataset.map(parse_fn, num_parallel_calls=tf.data.experimental.AUTOTUNE)
dataset = dataset.batch(3)

In [51]:
for x, y in dataset:
    print(type(x), x.shape)
    print(type(y), y.shape)
    break

<class 'tensorflow.python.framework.ops.EagerTensor'> (3, 1024, 1024, 3)
<class 'tensorflow.python.framework.ops.EagerTensor'> (3, 14)


In [56]:
import tensorflow as tf
import csv

def makeDataset(x_path, csv_filename, batch_size):
#     x_path = './sample/images/'
    x_file_list = []
    y_str_list = []
    with open(csv_filename) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        line_count = 0
        for row in csv_reader:
            if line_count == 0:
                line_count += 1
            else:
    #             print(type(row), len(row), row[0], row[1].split('|'))
                line_count += 1
                x_file_list.append(x_path + row[0])
                y_str_list.append(row[1].split('|'))

    y_dict = {
        'Emphysema': 0, 
        'Infiltration': 1, 
        'Pleural_Thickening': 2, 
        'Pneumothorax': 3, 
        'Cardiomegaly': 4, 
        'Atelectasis': 5, 
        'Edema': 6, 
        'Effusion': 7, 
        'Consolidation': 8, 
        'Mass': 9, 
        'Nodule': 10, 
        'Fibrosis': 11, 
        'Pneumonia': 12, 
        'Hernia': 13
    }
    # stats_dict = {}
    # for i in range(len(y_str_list)):
    #     labels = y_str_list[i]
    #     for label in labels:
    #         if label in stats_dict:
    #             stats_dict[label] += 1
    #         else:
    #             stats_dict[label] = 1
    # print(stats_dict)
    # print(len(stats_dict))
    y_list = []
    for i in range(len(y_str_list)):
        labels = [0] * 14
        for y_logit in y_str_list[i]:
            if y_logit == 'No Finding':
                continue
            labels[y_dict[y_logit]] = 1
        labels = tf.constant(labels)
        y_list.append(labels)
    dataset = tf.data.Dataset.from_tensor_slices((x_file_list, y_list))
    # for x in dataset_x:
    #     print(x)
    #     break
    def parse_fn(filename, label):
        img_str = tf.io.read_file(filename)
        img_dcd = tf.image.decode_png(img_str, channels=3)
        return img_dcd, label
    dataset = dataset.map(parse_fn, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    dataset = dataset.batch(batch_size)
    return dataset

if __name__ == '__main__':
    x_path = './sample/images/'
    csv_file = './sample/sample_labels.csv'
    batch_size = 3
    dataset = makeDataset(x_path, csv_file, batch_size)
    for x, y in dataset:
        print(x.shape, y.shape)
        break

(3, 1024, 1024, 3) (3, 14)
